version: '3'
services:
  go:
    build:
      context: backend
      dockerfile: build/Dockerfile
    # volumes:
    #   - ./golang:/root
    ports:
      - "8000:8000"
  #   depends_on: 
  #     - postgres
  # postgres:
  #   container_name: 'database_container'
  #   image: postgres:latest
  #   networks:
  #     - db_network
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   ports:
  #     - 5432:5432
  
# networks:
#   db_network:
#     driver: bridge
  
# volumes:
#   postgres_data:
