version: '3'
services:
  go:
    build:
      context: backend
      dockerfile: build/Dockerfile
    # volumes:
    #   - ./golang:/root
    networks:
      - db_network
    depends_on: 
      - db
    ports:
      - "8000:8000"

  db:
    container_name: 'database_container'
    image: postgres:latest
    networks:
      - db_network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
       - backend/.env
  
networks:
  db_network:
    driver: bridge
  
volumes:
  postgres_data:
