name: Development Workflow
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      # - name: Build code
      #   run: go build -v ./...
      - name: Lint
        run: |
          # binary will be $(go env GOPATH)/bin/golangci-lint
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.2
          golangci-lint --version
      #- name: List directories
      #  run: ls
      - name: Test code
        run: go test -v ./...
        working-directory: backend
      - name: Test code coverage
        run: go test -v -coverprofile cover.out ./...
        working-directory: backend