name: Development Workflow
on:
  push:
    branches-ignore:
      - main
jobs:
  Run golang tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Test code
        run: go test -v ./...