name: Development Workflow
on:
  push:
    branches-ignore:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      # - name: Build code
      #   run: go build -v ./...
      - name: List directories
        run: ls
      - name: Go to backend folder
        name: cd backend
      - name: Test code
        run: go test -v ./...